version: '3'

services:
  manager:
    image: docker:dind
    privileged: true
    ports:
      - "2375:2375"
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9094:9094"
  node:
    image: docker:dind
    privileged: true
